[project]
name = "mini-chrome-plugin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.20"
dependencies = [
    "flask>=2.0.0",
    "flask-cors>=4.0.0",
    "requests>=2.25.0"
]
